### ISSUE TITLE
Blank WPF window

### ISSUE THREAD

**Issue by mikau16** [MonoMaxMW/MonoMax.OpenGLWpfDemo#1]
Hello,

Thanks for this great initiative. 

The project builds fine but only a blank white wpf window is shown with no GL viewport. It looks like I should be seeing a light blue background based on your code.

I confirmed it is hitting the rendering loop, and GL.Clear is being called, along with GL.Viewport when resizing.

The following is logged to Output window (but  I think it may be benign):

Error:InvalidFramebufferOperationExt
Error:NoError
Error:NoError
Error:NoError
Error:NoError
Error:NoError
Error:NoError
Error:NoError
Error:NoError

**Comment by MonoMaxMW** [comment]
Hello guys,

Sorry when uploading the project I must have missed a couple of things. I’ll upload the working cleaned code this week. I’ll notify you guys. You can reach out to me either via this thread or discord

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mikau16** [comment]
Thanks a whole bunch I really appreciate this. Real excited to get my hands on this!

I left a message on the #development channel on the OpenTK discord, maybe you'd like to comment.

**Comment by MonoMaxMW** [comment]
Check my newest update should be fixed now
